### ISSUE TITLE
Kubetool 3.0.0 crashes unabled to read hostname-server.pem

### ISSUE THREAD

**Issue by kienanstewart** [puppetlabs/puppetlabs-kubernetes#168]
## What you expected to happen?

When running `docker run --rm -v $(pwd):/mnt --env-file .env puppet/kubetool:3.0.0` I expect it to finish without error.

## What happened?

Create certs crashed, unable to read the server certificates from file.

```
docker run --rm -v $(pwd):/mnt --env-file .env puppet/kubetool:3.0.0
/usr/bin/cfssl
Creating etcd ca
2018/10/04 19:17:42 [INFO] generating a new CA key and certificate from CSR
2018/10/04 19:17:42 [INFO] generate received request
2018/10/04 19:17:42 [INFO] received CSR
2018/10/04 19:17:42 [INFO] generating key: rsa-2048
2018/10/04 19:17:42 [INFO] encoded CSR
2018/10/04 19:17:42 [INFO] signed certificate with serial number 263467903853981777106031379089335872914386696860
Creating etcd client certs
2018/10/04 19:17:42 [INFO] generate received request
2018/10/04 19:17:42 [INFO] received CSR
2018/10/04 19:17:42 [INFO] generating key: rsa-2048
2018/10/04 19:17:42 [INFO] encoded CSR
2018/10/04 19:17:42 [INFO] signed certificate with serial number 203213226858113760732288002600610907065875654557
Creating etcd peer and server certificates
not enough arguments are supplied --- please refer to the usage
not enough arguments are supplied --- please refer to the usage
/etc/k8s/kube_tool/create_certs.rb:62:in `read': No such file or directory @ rb_sysopen - "kube01.local-server.pem (Errno::ENOENT)
        from /etc/k8s/kube_tool/create_certs.rb:62:in `block in etcd_server'
        from /etc/k8s/kube_tool/create_certs.rb:47:in `each'
        from /etc/k8s/kube_tool/create_certs.rb:47:in `etcd_server'
        from /etc/k8s/kube_tool.rb:67:in `build_hiera'
        from /etc/k8s/kube_tool.rb:77:in `<main>'
```

## How to reproduce it?

Module version: 3.0.1

`.env` contents: 
```
OS=Debian
VERSION="1.12"
CONTAINER_RUNTIME=docker
CNI_PROVIDER=weave
ETCD_INITIAL_CLUSTER="kube01.local:192.168.122.2,kube02.local:192.168.122.10,kube03.local:192.168.122.11"
ETCD_IP="%{::ipaddress_eth1}"
KUBE_API_ADVERTISE_ADDRESS="%{::ipaddress_eth1}"
INSTALL_DASHBOARD=true
```

Note: I tried with 'VERSION' 1.11 as well. There also isn't a published docker image for puppet/kubetool:3.0.1 so I used the closest possible version.

## Anything else we need to know?

I tried older puppet/kubetool images, and 1.02 "worked" in that it didn't completely crash. I imagine it won't produce output that is compatible with the puppetlabs/kubernetes module v3.0.1

## Versions:

$ docker version OR crictl version

`docker-ce: 18.06.1~ce~3-0~debian`

$ facter os

```
{
  architecture => "amd64",
  distro => {
    codename => "sid",
    description => "Debian GNU/Linux unstable (sid)",
    id => "Debian",
    release => {
      full => "unstable",
      major => "unstable"
    }
  },
  family => "Debian",
  hardware => "x86_64",
  name => "Debian",
  release => {
    full => "buster/sid",
    major => "buster/sid"
  },
  selinux => {
    enabled => false
  }
}
```

**Comment by kienanstewart** [comment]
Worked without the quotes on ETCD_INITIAL_CLUSTER. Thanks!
