### ISSUE TITLE
docker commands fail with errors

### ISSUE THREAD

**Issue by gameforce** [puppetlabs/puppetlabs-kubernetes#604]
## What happened?

```
Error:
/etc/k8s/kube_tool/other_params.rb:15:in `create': undefined method `[]' for nil:NilClass (NoMethodError)
        from /etc/k8s/kube_tool.rb:67:in `build_hiera'
        from /etc/k8s/kube_tool.rb:82:in `<main>'

```
## How to reproduce it?
Run this
`docker run --rm -v $(pwd):/mnt --env-file env puppet/kubetool:6.2.0`

## Anything else we need to know?
Latest docker image (6.2.0) doesn't match module version (6.3.0) last update was a year ago. I'm assuming this project has been abandoned. I wish it wasn't.

**Comment by deric** [comment]
@gameforce You should copy the whole example from the README. I know, it's a long line.

```
docker run --rm -v $(pwd):/mnt -e OS=Debian -e VERSION=1.26.0 -e CONTAINER_RUNTIME=docker -e CNI_PROVIDER=cilium -e CNI_PROVIDER_VERSION=1.4.3 -e ETCD_INITIAL_CLUSTER=kube-control-plane:172.17.10.101,kube-replica-control-plane-01:172.17.10.210,kube-replica-control-plane-02:172.17.10.220 -e ETCD_IP="%{networking.ip}" -e KUBE_API_ADVERTISE_ADDRESS="%{networking.ip}" -e INSTALL_DASHBOARD=true puppet/kubetool:6.2.0
```
Unfortunately the version `6.3.0` hasn't been tagged on Docker hub (#546 hasn't been resolved).

Alternatively you can checkout the module repo and build the tool locally:

```
git clone https://github.com/puppetlabs/puppetlabs-kubernetes.git
cd puppetlabs-kubernetes/tooling
docker build -t puppet/kubetool .
```
The CLI has been refactored in #593, hopefully it's more user-friendly (let me know if you run into any problems)
```
$ docker run --rm -v $(pwd):/mnt puppet/kubetool:latest -h
usage: /etc/k8s/kube_tool.rb [options]
    -o, --os                    The OS that Kubernetes will run on
    -v, --version               The Kubernetes version to install
    -r, --container_runtime     The container runtime to use. This can only be "docker" or "cri_containerd"
    -c, --cni_provider          The networking provider to use, flannel, weave, calico, calico-tigera or cilium are supported
    -p, --cni_provider_version  The networking provider version to use, calico and cilium will use this to reference the correct deployment download link
    -t, --etcd_ip               The IP address etcd will listen on
    -i, --etcd_initial_cluster  The list of servers in the etcd cluster
    -a, --api_address           The IP address (or fact) that kube api will listen on
    -b, --key_size              Specifies the number of bits in the key to create
    --ca_algo                   Algorithm to generate CA certificates, default: ecdsa
    --sa_size                   Service account key size
    -d, --install_dashboard     Whether install the kube dashboard
    -h, --help                  print the help
```

Though, providing etcd IP addresses and k8s version is a must.

**Comment by gameforce** [comment]
Thanks this worked, I used the build option for others trying to make it work, i.e. I built the tool then ran the full command line without the env file.
