### ISSUE TITLE
Not able to generate certificates -  undefined method `match' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by kavita1205** [puppetlabs/puppetlabs-kubernetes#675]
## Describe the Bug

We are trying to use puppetlabs kubernetes module 6.3.0 for below env file but when we are running docker command we are getting below error message:

env file
`OS=ubuntu
VERSION=1.27.11
CONTAINER_RUNTIME=cri_containerd
CNI_PROVIDER=calico
CNI_PROVIDER_VERSION=3.25
ETCD_INITIAL_CLUSTER=lv1-ml****-l06:10.150.***.*,lv1-ml***-l07:10.150.***,lv1-mlk****-l08:10.150.***.*
ETCD_IP="%{networking.ip}"
KUBE_API_ADVERTISE_ADDRESS="10.150.***.**"
INSTALL_DASHBOARD=true
`

Error message
`sudo docker run --rm -v $(pwd):/mnt --env-file env puppet/kubetool:6.3.0
/etc/k8s/kube_tool/other_params.rb:9:in `create': undefined method `match' for nil:NilClass (NoMethodError)
        from /etc/k8s/kube_tool.rb:67:in `build_hiera'
        from /etc/k8s/kube_tool.rb:82:in `<main>'
`
## Expected Behavior

It should able to generate certificate for kubetool version 6.3.0
## Steps to Reproduce
1. Copy above env file
2. Run below command- sudo docker run --rm -v $(pwd):/mnt --env-file env puppet/kubetool:6.3.0

## Environment
 - Version [e.g. 1.27.0]- 
 - Platform [e.g. Ubuntu 18.04]- Ubuntu22.04

**Comment by kavita1205** [comment]
Hi @carabasdaniel can you please help me here.
